"""
Dispatcher for multiple MPC solves
"""


import logging
import os
import sys
import traceback
from contextlib import contextmanager
from pathlib import Path
import ray

_PROJECT_ROOT = str(Path(__file__).resolve().parents[2])


def _resolve_ray_temp_dir() -> str:
    """Per-task scratch directory for Ray's session state.

    Fallback order:
      1. `$TMPDIR` (always set by PBS, unique per job).
      2. `$PBS_JOBFS` (cnode-local scratch on some Imperial queues).
      3. `/tmp` (last resort — collisions possible on shared nodes).
    """
    base = os.environ.get("TMPDIR") or os.environ.get("PBS_JOBFS") or "/tmp"
    jobid = os.environ.get("PBS_JOBID", "nopbs").replace("/", "_")
    array_idx = os.environ.get("PBS_ARRAY_INDEX", "0")
    path = Path(base) / f"ray-{jobid}-{array_idx}"
    path.mkdir(parents=True, exist_ok=True)
    return str(path)


def ensure_ray(num_cpus, **kwargs):
    """Idempotent Ray init. Call this exactly once per process, *before*
    JAX is imported or its BLAS/XLA threads are configured — Ray forks
    raylet/GCS subprocesses inside `ray.init()`, and forking a
    JAX-threaded parent deadlocks the children on inherited mutex
    state. Subsequent calls are no-ops, so it's safe to call from
    multiple entry points.
    """
    if ray.is_initialized():
        return

    os.environ.setdefault("RAY_gcs_server_request_timeout_seconds", "120")
    os.environ.setdefault("RAY_raylet_start_wait_time_s", "60")

    temp_dir = _resolve_ray_temp_dir()
    init_kwargs = dict(
        num_cpus=int(num_cpus),
        runtime_env={"env_vars": {"PYTHONPATH": _PROJECT_ROOT}},
        _metrics_export_port=None,
        logging_level=logging.ERROR,
        _temp_dir=temp_dir,
        _plasma_directory=temp_dir,
        object_store_memory=256 * 1024 * 1024,  # 256 MiB
        include_dashboard=False,
    )
    init_kwargs.update(kwargs)
    ray.init(**init_kwargs)


@contextmanager
def suppress_worker_output():
    with open(os.devnull, "w") as devnull:
        old_out, old_err = sys.stdout, sys.stderr
        gurobi_logger = logging.getLogger("gurobipy")
        old_gurobi_level = gurobi_logger.level
        sys.stdout, sys.stderr = devnull, devnull
        gurobi_logger.setLevel(logging.CRITICAL + 1)
        try:
            yield
        finally:
            sys.stdout, sys.stderr = old_out, old_err
            gurobi_logger.setLevel(old_gurobi_level)

class RayMultiMPC:
    def __init__(self, env_args, param_overrides, num_instances, num_devices, timeout, exit_fraction, dump_diagnostics_on_failure=False, log_dir=None, master_seed=None):
        self._env_args = env_args
        self._params = param_overrides
        self._num_instances = num_instances
        self._timeout = timeout
        self._exit_fraction = exit_fraction
        self._dump_diagnostics = dump_diagnostics_on_failure
        self._master_seed = master_seed

        self._worker_log_dir = None
        if log_dir is not None:
            self._worker_log_dir = Path(log_dir) / "worker_logs"
            self._worker_log_dir.mkdir(parents=True, exist_ok=True)

        # Populated by run_multisim — per-worker total_tonnes in env units.
        self.last_total_tonnes: list = []

        # Idempotent — see `ensure_ray` docstring. We do NOT shutdown
        # between BO iters: Ray's raylet/GCS startup forks subprocesses,
        # and forking once JAX has spun up BLAS/XLA threads in this
        # process deadlocks the children.
        ensure_ray(num_cpus=num_devices)

    def run_multisim(self, deadline=None, progress_callback=None):
        import time as _time
        from hydro_bo.utils.logging_config import get_logger
        from collections import Counter

        logger = get_logger(__name__)
        start_time = _time.perf_counter()

        worker_log_dir = str(self._worker_log_dir) if self._worker_log_dir is not None else None
        if self._master_seed is None:
            from hydro_bo.utils.seeding import resolve_master_seed
            self._master_seed = resolve_master_seed(None)
            logger.info("dispatcher.master_seed_autogenerated", master_seed=self._master_seed)
        else:
            logger.info("dispatcher.master_seed", master_seed=self._master_seed)
        tasks = [run_mpc.remote(self._env_args, id=f"iter_{i}", params=self._params, dump_diagnostics=self._dump_diagnostics, log_dir=worker_log_dir, master_seed=self._master_seed) for i in range(self._num_instances)]
        ref_to_idx = {ref: i for i, ref in enumerate(tasks)}

        # Sentinel for cancelled / failed-ray-get rows. 4-tuple to match
        # the worker return shape (success, score, total_tonnes, relax_info).
        _FAILED = (False, None, 0.0, None)

        def _emit(idx, result):
            if progress_callback is None:
                return
            success, score, _, relax_info = result
            try:
                progress_callback(idx, success, score, relax_info)
            except Exception:
                logger.exception("progress_callback_failed", worker_index=idx)

        if self._dump_diagnostics:
            results = []
            for i, task in enumerate(tasks):
                result = ray.get([task])[0]
                results.append(result)
                _emit(i, result)
                success, _, _, _ = result
                if not success:
                    logger.info("early_exit_on_failure", task_index=i, reason="Diagnostic dump requested")
                    for remaining_task in tasks[i+1:]:
                        ray.cancel(remaining_task)
                        _emit(ref_to_idx[remaining_task], _FAILED)
                    break
        elif deadline is not None:
            results = []
            pending = list(tasks)
            stopped_early = False
            while pending:
                remaining = deadline - _time.perf_counter()
                if remaining <= 0:
                    stopped_early = True
                    break
                ready, pending = ray.wait(pending, num_returns=1, timeout=min(remaining, 10.0))
                for ref in ready:
                    try:
                        res = ray.get(ref)
                    except Exception:
                        # `None` (YAML/JSON null) marks the score field as a
                        # failed run — downstream consumers coerce to NaN.
                        res = _FAILED
                    results.append(res)
                    _emit(ref_to_idx[ref], res)
            if stopped_early:
                n_cancelled = len(pending)
                logger.info("deadline_reached", n_completed=len(results), n_cancelled=n_cancelled)
                for ref in pending:
                    ray.cancel(ref)
                    _emit(ref_to_idx[ref], _FAILED)
                # Pad with failure entries for cancelled tasks
                results.extend([_FAILED] * n_cancelled)
        elif progress_callback is not None:
            results = []
            pending = list(tasks)
            while pending:
                ready, pending = ray.wait(pending, num_returns=1)
                for ref in ready:
                    try:
                        res = ray.get(ref)
                    except Exception:
                        res = _FAILED
                    results.append(res)
                    _emit(ref_to_idx[ref], res)
        else:
            results = ray.get(tasks)

        scores = [score for _, score, _, _ in results]
        # Per-worker total_tonnes (raw env units; see ShippingEnv for unit
        # semantics). Stashed for callers that want the distribution
        # (e.g., scripts/multi_mpc.py); `run_multisim` still returns
        # scores for backward compat with the BO scripts.
        self.last_total_tonnes = [t for _, _, t, _ in results]
        n_success = sum(1 for success, _, _, _ in results if success)

        all_relaxations = []
        for _, _, _, relax_info in results:
            if relax_info and 'relaxations_used' in relax_info:
                all_relaxations.extend(relax_info['relaxations_used'])

        relaxation_counts = Counter(all_relaxations)
        elapsed = _time.perf_counter() - start_time

        logger.info("multisim_complete",
                   n_success=n_success,
                   n_total=self._num_instances,
                   elapsed_seconds=elapsed,
                   relaxation_usage=dict(relaxation_counts))

        return scores

@ray.remote
def run_mpc(env_args, id, params, dump_diagnostics=False, log_dir=None, master_seed=None):
    import socket
    import structlog
    import warnings
    from hydro_bo import ShippingEnv
    from hydro_bo.utils.logging_config import configure_logging, get_logger
    from hydro_bo.utils.seeding import derive_worker_seed, derive_subseed

    if log_dir is not None:
        worker_log_path = Path(log_dir) / f"{id}.log"
        configure_logging(log_file=worker_log_path, tee_stderr=False)
    else:
        _devnull = open(os.devnull, "w")
        structlog.configure(logger_factory=structlog.PrintLoggerFactory(file=_devnull))

    pyomo_logger = logging.getLogger("pyomo.core")
    pyomo_logger.setLevel(logging.CRITICAL + 1)

    warnings.filterwarnings("ignore", category=UserWarning, module="pyomo")
    warnings.filterwarnings("ignore", message=".*Loading a SolverResults.*")
    warnings.filterwarnings("ignore", message=".*termination condition.*")

    if master_seed is None:
        from hydro_bo.utils.seeding import resolve_master_seed
        master_seed = resolve_master_seed(None)

    ctx = ray.get_runtime_context()
    ray_task_id = ctx.get_task_id()
    seed = derive_worker_seed(master_seed, ray_task_id)

    worker_logger = get_logger(__name__)
    worker_logger.info(
        "worker.seed_derived",
        worker_id=id,
        master_seed=master_seed,
        worker_seed=seed,
        ray_task_id=ray_task_id,
        pbs_jobid=os.environ.get("PBS_JOBID", ""),
        pbs_array_index=os.environ.get("PBS_ARRAY_INDEX", ""),
        pid=os.getpid(),
        hostname=socket.gethostname(),
        sub_seeds={
            "weather": derive_subseed(seed, "weather"),
            "dynamics": derive_subseed(seed, "dynamics"),
            "price": derive_subseed(seed, "price"),
            "gurobi": derive_subseed(seed, "gurobi"),
        },
    )

    def _deep_set(target, updates):
        for k, v in updates.items():
            if isinstance(v, dict):
                if k not in target or not isinstance(target[k], dict):
                    target[k] = {}
                _deep_set(target[k], v)
            else:
                target[k] = v

    env = None
    total_reward = 0.0
    total_tonnes = 0.0
    try:
        env = ShippingEnv('shipping')
        with env as e:
            _deep_set(e, env_args.get("config", {}))
            e['seed'] = seed
            e['mpc']['planning_model'] = params

        while True:
            with suppress_worker_output():
                observation, reward, done, info = env.step(None)
            total_reward += reward
            total_tonnes += observation.get("total_tonnes", 0.0)

            call_count = info.get("call_count") if isinstance(info, dict) else None

            if done or (call_count is not None and call_count >= 12):
                # Get relaxation history to return
                relaxation_info = None
                if hasattr(env, 'mpc') and hasattr(env.mpc, 'relaxation_tree'):
                    history = env.mpc.relaxation_tree.get_history()
                    relaxation_info = {
                        'total_relaxations': len(history),
                        'relaxations_used': [h['name'] for h in history]
                    }

                # Zero tonnes shipped → degenerate run, marked as a failure
                # via `None` so it's distinguishable from a finite low score.
                score = total_reward / total_tonnes if total_tonnes > 0 else None
                return True, score, total_tonnes, relaxation_info

    except Exception as e:
        print(
            f"[Worker {id}] {type(e).__name__}: {e}\n"
            + traceback.format_exc(),
            file=sys.stderr,
            flush=True,
        )

        relaxation_info = None
        if env is not None and hasattr(env, 'mpc') and hasattr(env.mpc, 'relaxation_tree'):
            history = env.mpc.relaxation_tree.get_history()
            relaxation_info = {
                'total_relaxations': len(history),
                'relaxations_used': [h['name'] for h in history]
            }

        if dump_diagnostics and env is not None and hasattr(env, 'mpc'):
            try:
                env.mpc._diagnose_infeasibility()
                print(f"[Worker {id}] Diagnostic files saved for failed run", file=sys.stderr, flush=True)
            except Exception as diag_error:
                print(f"[Worker {id}] Failed to save diagnostics: {diag_error}", file=sys.stderr, flush=True)

        return False, None, total_tonnes, relaxation_info
